name: flutter_local_notifications_example
description: Demonstrates how to use the flutter_local_notifications plugin.
publish_to: none

dependencies:
  cupertino_icons: ^1.0.8
  device_info_plus: 
    git: https://github.com/kumsumit/device_info_plus.git
  flutter:
    sdk: flutter
  flutter_local_notifications:
    path: ../
  flutter_timezone: 
    git: https://github.com/kumsumit/flutter_timezone.git
  http: ^1.1.0
  image: 
    git: https://github.com/kumsumit/image.git
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  timezone: ^0.10.0  


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  msix: ^2.7.3

flutter:
  uses-material-design: true
  assets:
    - icons/
    - sound/

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"
  
msix_config:
  display_name: Flutter Local Notifications Example
  identity_name: Com.Example.FlutterLocalNotificationsExample
  msix_version: 1.0.0.0
  store: false
  install_certificate: false
  output_name: example
  toast_activator:
    clsid: "d49b0314-ee7a-4626-bf79-97cdb8a991bb"
    arguments: "msix-args"
    display_name: "Flutter Local Notifications"